### ISSUE TITLE
Password input printed to stdout

### ISSUE THREAD

**Issue by pablosichert** [jedisct1/piknik#33]
Hey there!

Currently, when using the `-genkeys -password` option, the password input is printed to stdout:

```
$ piknik -genkeys -password
Password> MY_PASSWORD_IN_PLAIN_TEXT
```

I think it would be nicer to supress the output, as unix CLIs commonly do for password inputs.

**Comment by jedisct1** [comment]
Yes, this is intentional.

This makes it easier to use and type long passphrases. 

Typing passwords in the blind made sense when passwords used to be limited to 8 characters and smartphones didn't exist. But nowadays, they are more of an annoyance than something that improves security.
Even more for passwords you only type once.
