### ISSUE TITLE
Consider 5-digit default port

### ISSUE THREAD

**Issue by ImportTaste** [jedisct1/piknik#38]
Windows aggressively reserves 4-digit ports unless you use a command like:
```batch
netsh int ipv4 add excludedportrange protocol=tcp startport=8075 numberofports=1
```
And, this command only works if the port hasn't already been reserved (so it's best ran after startup).

Changing the default port to something like 18075 would prevent Windows users from running into unexpected difficulty hosting or connecting with piknik.

**Comment by jedisct1** [comment]
Hi!

You can change the port to any port in the configuration file.

I don't think changing the default port is a good idea, especially since higher ports may be reserved to other applications on other systems.

Connecting to a remote piknik server on any ports doesn't seem to require any configuration. I'm using it that way all the time :)

If receiving traffic to a specific port requires a command, maybe this is something we should document instead. Would you mind submitting a PR to update the documentation with relevant instructions?
