### ISSUE TITLE
A big thanks and several small things.

### ISSUE THREAD

**Issue by g40** [jedisct1/piknik#42]
Excellent and most practical for Host/Guest virtual machine communication. Worked out of the box with one minor (Windows server side tweak). On Windows piknik.toml is not a dot file and lives in %USERPROFILE%\piknik.toml. 

So: Many thanks.

2 questions: 
I'm not a Go guy - what is best way way to install the built from source binaries on Ubuntu Linux and Windows 10? Just copy the binary to a suitable folder?
And might it be possible to have the Windows version of the server listen out for clipboard change notifications? Then a standard `File >> Copy` would (optionally) automatically get broadcast to all peers? https://learn.microsoft.com/en-us/windows/win32/dataxchg/wm-clipboardupdate [edit] A quick search shows this to be non-trivial.

**Comment by jedisct1** [comment]
Hi,

Yes, copy the executable file anywhere in your path, and to uninstall it, just delete the file. Nothing else needed.

Indeed, on Windows, the config file is simply named `piknik.toml`, because I don't think Windows supports files starting with a dot (or if it does, that would be very unusual). If this is not documented, this is something that should be mentioned.

Listening to clipboard change notifications on Windows could be cool, but unfortunately I have no experience with Windows.

**Comment by g40** [comment]
Thanks for listening. Appreciated.
